board/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.mainPage),
    path('mp4', views.mp4),
    path('aws', views.aws),
]

config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('board/', include('board.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pybo/urls.py
from django.urls import path

from . import views

app_name = 'pybo'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
]

sean/urls.py
from django.urls import path
from . import views

urlpatterns = []

board/models.py
from django.db import models

# Create your models here.

class Math(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()

    def __str__(self):
        return 'subject = {}, content = {}'.format(self.subject, self.content)

pybo/models.py
from django.db import models

# Create your models here.

class Question(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()

    def __str__(self):
        return self.subject

class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()

class MyModel(models.Model):
    # MEDIA_ROOT/uploads/ 경로로 파일 업로드
    upload = models.FileField(upload_to = 'uploads/')
    # or
    # MEDIA_ROOT/uploads/2021/01/01 경로로 파일 업로드
    upload = models.FileField(upload_to = 'uploads/%Y/%m/%d/')

sean/models.py
from django.db import models

# Create your models here.

board/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Math
# Create your views here.

def mainPage(request):
    maths = Math.objects.all()
    context = {'maths': maths}
    return render(request, 'board/index.html',context)

def index(request):
    return HttpResponse("welcome to my world")

def mp4(request):
    return render(request, 'board/mp4.html')

def aws(request):
    return render(request, 'board/awsimage.html')

pybo/views.py
# Create your views here.
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .models import Question

def index(request):
    question_list = Question.objects.order_by('-create_date')
    context = {'question_list': question_list}
    return render(request, 'pybo/question_list.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'pybo/question_detail.html', context)

def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    question.answer_set.create(content=request.POST.get('content'), create_date=timezone.now())
    return redirect('pybo:detail', question_id=question.id)

sean/views.py
from django.shortcuts import render

# Create your views here.

templates/board/awsimage.html
<!DOCTYPE html>
<html>
<body>

<img src="/static/img/Unknown.png">
</body>
</html>

templates/board/index.html
<body>
    {% if maths %}
    {% for math in maths %}
        {{ math }}    <br />
        {{ math.subject }} <br />
        {{ math.content }} <br />
    {% endfor %}
    {% else %}
    <tr>
        <td colspan="3">질문이 없습니다.</td>
    </tr>
    {% endif %}
</body>

templates/board/mp4.html
<!DOCTYPE html>
<html>
<body>

<img src="/static/img/Unknown.png">
<img src="/static/img/lol.mp4">
</body>
</html>

templates/pybo/mp4.html
<!-- For a static file -->
<video width="320" height="240" controls>
    <source src="{% static 'path/to/your/video.mp4' %}" type="video/mp4">
    Your browser does not support the video tag.
  </video>
  
  <!-- For a media file -->
  <video width="320" height="240" controls>
    <source src="{{ MEDIA_URL }}path/to/your/video.mp4" type="video/mp4">
    Your browser does not support the video tag.
  </video>

templates/pybo/question_detail.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

<h1>{{ question.subject }}</h1>
<div>
    {{ question.content }}
</div>

<h5>{{ question.answer_set.count }}개의 답변이 있습니다.</h5>
<div>
    <ul>
    {% for answer in question.answer_set.all %}
        <li>{{ answer.content }}</li>
    {% endfor %}
    </ul>
</div>

<form action="{% url 'pybo:answer_create' question.id %}" method="post">
{% csrf_token %}
<textarea name="content" id="content" rows="15"></textarea>
<input type="submit" value="답변등록">
</form>

templates/pybo/question_list.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="table-dark">
            <th>번호</th>
            <th>제목</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>
                <a href="{% url 'pybo:detail' question.id %}">{{ question.subject }}</a>
            </td>
            <td>{{ question.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
</div>